_target_: flatcfm.perturbench.flow_matching.FlatCFMFlowMatching
n_genes: null
n_perts: null
hidden_dim: 256
hidden_layers: 4
condition_dim: 128
embedding_dim: 64
projection_dim: 64
ode_method: rk4
ode_time: 1.0
lr: 1e-4
wd: 0.0
