"""analysis helpers"""

from .benchmarks import (
    Evaluation,
    Evaluator,
    MetricSpaceSpec,
    aggregate_adata,
    compute_metric,
    list_available_aggregations,
    list_available_metrics,
    prepare_metric_space_views,
    reduce_group_metrics,
)
from .benchmarking import (
    BenchmarkSuiteSpec,
    aggregate_over_runs,
    build_flow_evaluation,
    build_perturbench_style_evaluator,
    compute_benchmark_group_metrics,
    compute_flow_summary_metrics,
    compute_grouped_flow_metrics,
    compute_per_perturbation_space_metrics,
    evaluate_flow_predictions,
    format_mean_std_table,
    resolve_experiment,
    run_benchmark_suite,
    run_benchmark,
    select_benchmark_backend,
    validate_run_dirs,
)
from .flow_results import (
    FlowRunBundle,
    build_flow_distribution_views,
    get_flow_prediction_bundle,
    get_or_build_flow_predictions,
    load_flow_predictions,
    load_flow_run,
    select_heldout_perturbation,
)
from .prediction_export import PredictionArtifacts, build_prediction_adata, save_prediction_artifacts
from .perturbench_adapter import PerturbBenchTaskMetadata, evaluator_to_task_metadata, to_perturbench_predictions
from .toy import build_toy_scatter_payload, load_toy_prediction_adata

__all__ = [
    "Evaluation",
    "Evaluator",
    "BenchmarkSuiteSpec",
    "FlowRunBundle",
    "MetricSpaceSpec",
    "PredictionArtifacts",
    "PerturbBenchTaskMetadata",
    "aggregate_adata",
    "aggregate_over_runs",
    "build_flow_evaluation",
    "build_perturbench_style_evaluator",
    "build_flow_distribution_views",
    "build_toy_scatter_payload",
    "build_prediction_adata",
    "compute_benchmark_group_metrics",
    "compute_grouped_flow_metrics",
    "compute_metric",
    "compute_per_perturbation_space_metrics",
    "compute_flow_summary_metrics",
    "evaluate_flow_predictions",
    "evaluator_to_task_metadata",
    "format_mean_std_table",
    "get_flow_prediction_bundle",
    "get_or_build_flow_predictions",
    "load_flow_predictions",
    "list_available_aggregations",
    "list_available_metrics",
    "load_toy_prediction_adata",
    "load_flow_run",
    "run_benchmark",
    "run_benchmark_suite",
    "save_prediction_artifacts",
    "select_benchmark_backend",
    "select_heldout_perturbation",
    "validate_run_dirs",
    "prepare_metric_space_views",
    "reduce_group_metrics",
    "resolve_experiment",
    "to_perturbench_predictions",
]
