perturbation:
  name: perturbation
  source_column: perturbation
  encoding: categorical
control_column: vehicle
control_value: 1.0
perturbation_covariates: []
sample_covariates: []
output_obs_map:
  perturbation: condition
